version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

#  backend:
#    image: asterrus/foodgram_backend:v1.0.first
#    restart: always
#    volumes:
#      - static_value:/app/backend_static/
#      - media_value:/app/media/
#    depends_on:
#      - db
#    env_file:
#      - ./.env

volumes:
  db_value:
