"""timezone change

Revision ID: 1742a61b2cc8
Revises: 710ad76f34d5
Create Date: 2023-05-17 20:32:34.281591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1742a61b2cc8'
down_revision = '710ad76f34d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
